services:
  - type: web
    name: urban-air
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn urbanair.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: UrbanAir
      - key: APP_DEBUG
        value: false
      - key: SITE_URL
        sync: false
      - key: APP_STORAGE_PATH
        value: data/urbanair.db
      - key: WAQI_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
