from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CityFAQ:
    question: str
    answer: str


@dataclass(frozen=True)
class CityConfig:
    slug: str
    name: str
    state: str
    lat: float
    lon: float
    timezone: str
    hero_title: str
    meta_description: str
    intro: str
    commuter_tip: str
    sensitive_tip: str
    affiliate_focus: str
    related_slugs: tuple[str, ...]
    faqs: tuple[CityFAQ, ...]


CITY_REGISTRY: dict[str, CityConfig] = {
    "mumbai": CityConfig(
        slug="mumbai",
        name="Mumbai",
        state="Maharashtra",
        lat=19.0760,
        lon=72.8777,
        timezone="Asia/Kolkata",
        hero_title="Mumbai outdoor air quality and best time to step out today",
        meta_description="Check Mumbai AQI now, today's best outdoor time, commute guidance, and simple health advice for walking, running, and ventilation.",
        intro="Mumbai conditions can shift quickly with traffic, sea breeze, and humidity. UrbanAir helps you decide when a walk, commute, or short errand feels safest.",
        commuter_tip="For Mumbai commuters, the cleanest window is often more useful than the daily average because rush-hour exposure can feel much worse.",
        sensitive_tip="If you have asthma, allergies, or travel with kids, use the best-time window rather than relying only on the current AQI number.",
        affiliate_focus="air purifiers and replacement filters",
        related_slugs=("pune", "ahmedabad", "surat"),
        faqs=(
            CityFAQ("Is Mumbai AQI bad all day?", "Not always. Conditions often change through the day, so the best two-hour window matters more than one headline number."),
            CityFAQ("When should I open windows in Mumbai?", "Use the ventilation recommendation and best-time window together. Shorter ventilation windows are safer on moderate days."),
        ),
    ),
    "delhi": CityConfig(
        slug="delhi",
        name="Delhi",
        state="Delhi",
        lat=28.6139,
        lon=77.2090,
        timezone="Asia/Kolkata",
        hero_title="Delhi AQI now and the best outdoor window for today",
        meta_description="Track Delhi AQI, today's best and worst outdoor hours, and clear advice for commuting, workouts, and home ventilation.",
        intro="Delhi residents often need more than a raw AQI number. UrbanAir highlights when conditions are least stressful for errands, commuting, and outdoor plans.",
        commuter_tip="In Delhi, even moderate-looking periods can feel harder near traffic corridors, so short exposure planning helps.",
        sensitive_tip="Sensitive users should watch for rising pollution trends, not just the current reading, before planning school runs or workouts.",
        affiliate_focus="masks and purifier bundles",
        related_slugs=("gurugram", "noida", "jaipur"),
        faqs=(
            CityFAQ("Can I run outside in Delhi today?", "Use the running recommendation and the best-time window together. High effort exercise should be avoided when air stress is elevated."),
            CityFAQ("Why compare Delhi now vs later today?", "Because hourly changes can create a safer workout or commute window even on a poor-air day."),
        ),
    ),
    "bengaluru": CityConfig(
        slug="bengaluru",
        name="Bengaluru",
        state="Karnataka",
        lat=12.9716,
        lon=77.5946,
        timezone="Asia/Kolkata",
        hero_title="Bengaluru outdoor conditions and the best time to go out today",
        meta_description="See Bengaluru AQI now, the best time for a walk or run, and practical guidance for ventilation and daily commuting.",
        intro="Bengaluru often feels more comfortable than hotter cities, but local traffic and hourly variation still affect when stepping outside feels best.",
        commuter_tip="A comfortable temperature does not always mean low air stress, so check the combined outdoor score before longer walks.",
        sensitive_tip="Families and allergy-prone users should prefer the highlighted best window for playtime and ventilation.",
        affiliate_focus="compact purifiers and HEPA filters",
        related_slugs=("mysuru", "hyderabad", "chennai"),
        faqs=(
            CityFAQ("Is Bengaluru good for outdoor workouts today?", "The workout answer depends on both AQI and the combined outdoor score, especially if conditions worsen later in the day."),
            CityFAQ("Should I trust only the current AQI in Bengaluru?", "No. A fast glance at the next 24 hours is more useful than a single point-in-time reading."),
        ),
    ),
    "chennai": CityConfig(
        slug="chennai",
        name="Chennai",
        state="Tamil Nadu",
        lat=13.0827,
        lon=80.2707,
        timezone="Asia/Kolkata",
        hero_title="Chennai AQI, heat stress, and today's best outdoor timing",
        meta_description="Check Chennai AQI, today's safest time to go outside, and simple advice for walkers, runners, and home ventilation.",
        intro="Chennai decisions are often shaped by both air quality and heat. UrbanAir combines both so you can plan short outdoor time more confidently.",
        commuter_tip="Heat can make a moderate-air day feel rougher, so check the outdoor score before afternoon errands.",
        sensitive_tip="Sensitive users should treat high humidity and rising pollution as a cue to shorten outdoor plans.",
        affiliate_focus="cooling fans and purifier combos",
        related_slugs=("bengaluru", "hyderabad", "kochi"),
        faqs=(
            CityFAQ("Why does Chennai sometimes feel worse than the AQI suggests?", "Heat and humidity can increase overall outdoor stress even when pollution is not extreme."),
            CityFAQ("When should I ventilate in Chennai?", "Use shorter ventilation windows during the highlighted best period rather than leaving windows open for long."),
        ),
    ),
    "hyderabad": CityConfig(
        slug="hyderabad",
        name="Hyderabad",
        state="Telangana",
        lat=17.3850,
        lon=78.4867,
        timezone="Asia/Kolkata",
        hero_title="Hyderabad AQI now and best time to step outside today",
        meta_description="Monitor Hyderabad AQI, compare the next 24 hours, and get fast guidance for commuting, exercise, and ventilation.",
        intro="Hyderabad can shift between comfortable and stressful outdoor conditions quickly. UrbanAir highlights the cleaner and easier parts of the day.",
        commuter_tip="Use the best-time window for errands and lighter commuting if the current period looks worse than the next few hours.",
        sensitive_tip="Children, older adults, and respiratory users should pay extra attention to any rising-pollution signal.",
        affiliate_focus="masks and room purifiers",
        related_slugs=("bengaluru", "chennai", "pune"),
        faqs=(
            CityFAQ("Can I cycle outside in Hyderabad today?", "Check the cycling recommendation and avoid the worst two-hour block when air stress is elevated."),
            CityFAQ("What is the most useful metric for Hyderabad?", "The combined outdoor score is usually more actionable than AQI alone for daily decisions."),
        ),
    ),
    "pune": CityConfig(
        slug="pune",
        name="Pune",
        state="Maharashtra",
        lat=18.5204,
        lon=73.8567,
        timezone="Asia/Kolkata",
        hero_title="Pune AQI now with today's best outdoor window",
        meta_description="See Pune AQI, best outdoor time, and practical recommendations for walking, cycling, and opening windows.",
        intro="Pune users often need a quick outdoor answer before work, workouts, or evening plans. UrbanAir keeps that decision on one screen.",
        commuter_tip="Short trips are often easiest during the highlighted best window rather than at a fixed daily time.",
        sensitive_tip="If you are sensitive to pollution, use the compare page to see whether waiting a bit improves conditions.",
        affiliate_focus="portable air purifiers",
        related_slugs=("mumbai", "hyderabad", "ahmedabad"),
        faqs=(
            CityFAQ("Is Pune good for cycling today?", "Cycling depends on both air conditions and overall stress, not just a mild-looking temperature."),
            CityFAQ("Why is the best window important in Pune?", "Because a small shift in timing can make commuting or workouts noticeably easier."),
        ),
    ),
    "kolkata": CityConfig(
        slug="kolkata",
        name="Kolkata",
        state="West Bengal",
        lat=22.5726,
        lon=88.3639,
        timezone="Asia/Kolkata",
        hero_title="Kolkata AQI and the best time today for outdoor activity",
        meta_description="Check Kolkata AQI now, today's best and worst outdoor hours, and recommendations for exercise, commuting, and ventilation.",
        intro="Kolkata outdoor comfort is shaped by both pollution and humidity. UrbanAir helps you pick the least stressful part of the day.",
        commuter_tip="Use the outdoor score if you are deciding whether to walk part of your route or stay indoors a bit longer.",
        sensitive_tip="High humidity can make pollution linger, so sensitive users should prefer shorter outdoor windows.",
        affiliate_focus="dehumidifier and purifier picks",
        related_slugs=("bhubaneswar", "patna", "guwahati"),
        faqs=(
            CityFAQ("Why does Kolkata ventilation advice change often?", "Because humidity and pollution together can shift the safest time to open windows."),
            CityFAQ("Is a moderate AQI always okay in Kolkata?", "Not necessarily. Heat and humidity can still make outdoor time feel tougher."),
        ),
    ),
    "ahmedabad": CityConfig(
        slug="ahmedabad",
        name="Ahmedabad",
        state="Gujarat",
        lat=23.0225,
        lon=72.5714,
        timezone="Asia/Kolkata",
        hero_title="Ahmedabad AQI now and today's best time to go outside",
        meta_description="Track Ahmedabad AQI, compare the next 24 hours, and get clear advice for walking, running, and indoor ventilation.",
        intro="Ahmedabad users often need quick answers during hot parts of the day. UrbanAir blends air quality and heat stress for more useful guidance.",
        commuter_tip="If the air is only moderate but the heat is high, the outdoor score is usually the better metric for errands.",
        sensitive_tip="Sensitive users should prefer short outdoor exposure and use the highlighted best block when possible.",
        affiliate_focus="cooling plus purification products",
        related_slugs=("surat", "mumbai", "jaipur"),
        faqs=(
            CityFAQ("Does Ahmedabad heat affect outdoor advice?", "Yes. Heat can reduce outdoor comfort even when AQI alone looks manageable."),
            CityFAQ("Should I walk outside now or later in Ahmedabad?", "Compare the current hour with the next best window before deciding."),
        ),
    ),
    "surat": CityConfig(
        slug="surat",
        name="Surat",
        state="Gujarat",
        lat=21.1702,
        lon=72.8311,
        timezone="Asia/Kolkata",
        hero_title="Surat AQI and today's best outdoor time",
        meta_description="Check Surat AQI, find the best time today for outdoor plans, and get simple activity and ventilation recommendations.",
        intro="Surat residents can use UrbanAir to decide when a walk, ride, or ventilation break makes the most sense over the next 24 hours.",
        commuter_tip="When conditions look mixed, use the best two-hour period instead of the daily average.",
        sensitive_tip="If anyone at home is sensitive to pollution, shorten outdoor exposure during the worst-time block.",
        affiliate_focus="home filters and purifier maintenance",
        related_slugs=("ahmedabad", "mumbai", "vadodara"),
        faqs=(
            CityFAQ("Is it safe to ventilate in Surat today?", "Use the ventilation recommendation for the current hour and the best window for timing."),
            CityFAQ("Why does Surat need hourly guidance?", "Because daily averages hide the most useful timing decisions."),
        ),
    ),
    "jaipur": CityConfig(
        slug="jaipur",
        name="Jaipur",
        state="Rajasthan",
        lat=26.9124,
        lon=75.7873,
        timezone="Asia/Kolkata",
        hero_title="Jaipur AQI now and today's best time for outdoor plans",
        meta_description="See Jaipur AQI, the next 24-hour outlook, and simple guidance for commuting, exercise, and opening windows.",
        intro="Jaipur users often need an easy view of when outdoor stress eases. UrbanAir highlights the most workable part of the day.",
        commuter_tip="The compare view helps when you are deciding between going now or waiting for a cleaner period.",
        sensitive_tip="Respiratory-sensitive users should avoid strenuous activity during the worst-time block.",
        affiliate_focus="anti-pollution masks",
        related_slugs=("delhi", "ahmedabad", "lucknow"),
        faqs=(
            CityFAQ("Can I run outside in Jaipur today?", "Use the running recommendation rather than AQI alone, especially on warmer days."),
            CityFAQ("What makes the best-time window useful in Jaipur?", "It helps convert a hard outdoor day into a shorter, lower-stress errand window."),
        ),
    ),
    "lucknow": CityConfig(
        slug="lucknow",
        name="Lucknow",
        state="Uttar Pradesh",
        lat=26.8467,
        lon=80.9462,
        timezone="Asia/Kolkata",
        hero_title="Lucknow AQI and the best outdoor window for today",
        meta_description="Check Lucknow AQI now, compare current vs later conditions, and get practical recommendations for daily outdoor decisions.",
        intro="Lucknow residents can use UrbanAir to quickly decide whether now is a good time to step out or whether the next window looks better.",
        commuter_tip="Short timing changes can make a bigger difference than expected, especially when pollution trends upward.",
        sensitive_tip="Sensitive users should watch the trend note closely before school runs, outdoor play, or exercise.",
        affiliate_focus="purifier and mask essentials",
        related_slugs=("kanpur", "delhi", "jaipur"),
        faqs=(
            CityFAQ("Why compare now vs later in Lucknow?", "Because near-term trend changes can make waiting worthwhile even on similar-looking days."),
            CityFAQ("Should I open windows in Lucknow today?", "Follow the ventilation recommendation and keep windows mostly closed during poor periods."),
        ),
    ),
    "kanpur": CityConfig(
        slug="kanpur",
        name="Kanpur",
        state="Uttar Pradesh",
        lat=26.4499,
        lon=80.3319,
        timezone="Asia/Kolkata",
        hero_title="Kanpur AQI now with simple outdoor guidance for today",
        meta_description="Track Kanpur AQI, best outdoor timing, and practical guidance for exercise, errands, and ventilation decisions.",
        intro="UrbanAir gives Kanpur users a faster answer than scanning raw AQI tables. It shows when outdoor time is least stressful today.",
        commuter_tip="If today's current score is weak, compare it with the best window before making longer outdoor plans.",
        sensitive_tip="People with breathing sensitivity should use the worst-time block as a strong avoid signal.",
        affiliate_focus="indoor air quality gear",
        related_slugs=("lucknow", "delhi", "patna"),
        faqs=(
            CityFAQ("Is Kanpur okay for a walk today?", "Use the walking recommendation and try to stay inside the highlighted better window."),
            CityFAQ("What should sensitive users do in Kanpur?", "Reduce strenuous activity and prefer shorter outdoor exposure when pollution stress is elevated."),
        ),
    ),
    "patna": CityConfig(
        slug="patna",
        name="Patna",
        state="Bihar",
        lat=25.5941,
        lon=85.1376,
        timezone="Asia/Kolkata",
        hero_title="Patna AQI now and today's better time to go outside",
        meta_description="Check Patna AQI, compare current and upcoming outdoor conditions, and get quick recommendations for daily activities.",
        intro="Patna users can use UrbanAir to turn AQI data into a simple timing decision for errands, school runs, and home ventilation.",
        commuter_tip="The best-time block is especially useful when the day overall looks poor but one short period improves.",
        sensitive_tip="Families should prefer short outdoor tasks during the highlighted better window whenever possible.",
        affiliate_focus="mask packs and purifier filters",
        related_slugs=("kolkata", "kanpur", "ranchi"),
        faqs=(
            CityFAQ("Can I exercise outside in Patna today?", "Only if the recommendation is favorable and the best window aligns with your schedule."),
            CityFAQ("Why does Patna need a compare page?", "It helps you see whether waiting reduces outdoor stress enough to matter."),
        ),
    ),
    "bhopal": CityConfig(
        slug="bhopal",
        name="Bhopal",
        state="Madhya Pradesh",
        lat=23.2599,
        lon=77.4126,
        timezone="Asia/Kolkata",
        hero_title="Bhopal AQI today with the best time to step out",
        meta_description="See Bhopal AQI now, today's best and worst outdoor hours, and practical activity guidance for daily use.",
        intro="UrbanAir helps Bhopal residents make quick timing decisions for walks, cycling, ventilation, and outdoor errands.",
        commuter_tip="Check the timeline before longer afternoon plans because conditions can change through the day.",
        sensitive_tip="Sensitive users should rely on both the current recommendation and the trend note before stepping out.",
        affiliate_focus="air purifiers and filter kits",
        related_slugs=("indore", "nagpur", "lucknow"),
        faqs=(
            CityFAQ("What is the best outdoor metric for Bhopal?", "The outdoor score is the easiest way to combine pollution and comfort into one decision."),
            CityFAQ("Should I cycle in Bhopal today?", "Use the cycling recommendation and avoid the worst-time period."),
        ),
    ),
    "indore": CityConfig(
        slug="indore",
        name="Indore",
        state="Madhya Pradesh",
        lat=22.7196,
        lon=75.8577,
        timezone="Asia/Kolkata",
        hero_title="Indore AQI now and best outdoor timing for today",
        meta_description="Track Indore AQI, the next 24-hour outdoor score, and simple guidance for commuting, workouts, and ventilation.",
        intro="Indore users can check one page to see when a walk or errand makes more sense and when to stay indoors longer.",
        commuter_tip="If the current hour looks weak, a small delay may line up with a noticeably better outdoor window.",
        sensitive_tip="Sensitive users should avoid relying on temperature alone when deciding whether it feels safe outside.",
        affiliate_focus="portable HEPA units",
        related_slugs=("bhopal", "ahmedabad", "nagpur"),
        faqs=(
            CityFAQ("When is the best time to walk in Indore today?", "The highlighted best window is the fastest answer, especially on moderate or poor-air days."),
            CityFAQ("Why does Indore need hourly AQI guidance?", "Because the most useful decision is often about timing, not a daily average."),
        ),
    ),
    "nagpur": CityConfig(
        slug="nagpur",
        name="Nagpur",
        state="Maharashtra",
        lat=21.1458,
        lon=79.0882,
        timezone="Asia/Kolkata",
        hero_title="Nagpur AQI now and today's best outdoor window",
        meta_description="Check Nagpur AQI, compare current and upcoming conditions, and get fast guidance for exercise and ventilation.",
        intro="Nagpur residents can use UrbanAir to see whether now is the right time for a walk, ride, commute, or window ventilation.",
        commuter_tip="On hotter days, the outdoor score is often more practical than AQI alone.",
        sensitive_tip="Sensitive users should shorten outdoor time when both heat and air stress rise together.",
        affiliate_focus="cooling and purification bundles",
        related_slugs=("bhopal", "hyderabad", "pune"),
        faqs=(
            CityFAQ("Can I ventilate my home in Nagpur today?", "Follow the ventilation recommendation and prefer the highlighted better period."),
            CityFAQ("What makes Nagpur advice different?", "Heat can materially change whether outdoor time feels comfortable enough."),
        ),
    ),
    "gurugram": CityConfig(
        slug="gurugram",
        name="Gurugram",
        state="Haryana",
        lat=28.4595,
        lon=77.0266,
        timezone="Asia/Kolkata",
        hero_title="Gurugram AQI now and the best time for outdoor errands today",
        meta_description="Monitor Gurugram AQI, today's best outdoor window, and practical advice for commuting, workouts, and ventilation.",
        intro="Gurugram users often need quick commute guidance more than a generic AQI chart. UrbanAir focuses on the timing decision.",
        commuter_tip="The highlighted best block can help you avoid the least comfortable commute segment of the day.",
        sensitive_tip="Sensitive users should avoid outdoor workouts if air stress is rising over the next few hours.",
        affiliate_focus="masks and air purifiers",
        related_slugs=("delhi", "noida", "jaipur"),
        faqs=(
            CityFAQ("Should I go for a run in Gurugram today?", "Only if the running recommendation stays favorable during the best-time window."),
            CityFAQ("Why is Gurugram useful on mobile?", "Most users need a fast answer for commuting and short outdoor decisions."),
        ),
    ),
    "noida": CityConfig(
        slug="noida",
        name="Noida",
        state="Uttar Pradesh",
        lat=28.5355,
        lon=77.3910,
        timezone="Asia/Kolkata",
        hero_title="Noida AQI now with simple outdoor planning for today",
        meta_description="Track Noida AQI, today's best and worst outdoor windows, and get clear guidance for daily activities and ventilation.",
        intro="UrbanAir helps Noida users decide whether to step out now or wait for a cleaner and easier period later today.",
        commuter_tip="The compare page is especially helpful for short commute timing decisions.",
        sensitive_tip="People with respiratory sensitivity should treat any rising trend as a sign to reduce exposure.",
        affiliate_focus="purifier filters and masks",
        related_slugs=("delhi", "gurugram", "lucknow"),
        faqs=(
            CityFAQ("When should I open windows in Noida?", "Use the ventilation recommendation and keep the window short during only-okay periods."),
            CityFAQ("Is Noida safe for cycling today?", "Use the cycling recommendation and avoid the worst block of the day."),
        ),
    ),
    "kochi": CityConfig(
        slug="kochi",
        name="Kochi",
        state="Kerala",
        lat=9.9312,
        lon=76.2673,
        timezone="Asia/Kolkata",
        hero_title="Kochi AQI and today's best time to go outside",
        meta_description="Check Kochi AQI now, the best outdoor window, and practical advice for walking, workouts, and ventilation.",
        intro="Kochi users can use UrbanAir to balance humidity, temperature, and air quality before planning outdoor time.",
        commuter_tip="Humidity can change comfort more than expected, so check the outdoor score before longer walks.",
        sensitive_tip="Sensitive users should use shorter ventilation windows and avoid high-effort exercise when stress rises.",
        affiliate_focus="dehumidifiers and purifier combos",
        related_slugs=("chennai", "bengaluru", "coimbatore"),
        faqs=(
            CityFAQ("Why is Kochi comfort not the same as AQI?", "Humidity can make the overall outdoor experience feel harder than AQI alone suggests."),
            CityFAQ("When should I walk outside in Kochi today?", "Try to align with the highlighted best-time block."),
        ),
    ),
    "coimbatore": CityConfig(
        slug="coimbatore",
        name="Coimbatore",
        state="Tamil Nadu",
        lat=11.0168,
        lon=76.9558,
        timezone="Asia/Kolkata",
        hero_title="Coimbatore AQI now and best outdoor timing for today",
        meta_description="See Coimbatore AQI, best outdoor time, and practical recommendations for commuting, workouts, and ventilation.",
        intro="Coimbatore users can quickly check whether now is suitable for outdoor time or whether the next few hours look better.",
        commuter_tip="The best-time block is more actionable than a daily average if you only need a short outdoor window.",
        sensitive_tip="Sensitive users should combine the trend note with the current activity recommendation before making plans.",
        affiliate_focus="room purifiers",
        related_slugs=("kochi", "chennai", "bengaluru"),
        faqs=(
            CityFAQ("Can I run outside in Coimbatore today?", "Use the running recommendation and the best-time window together."),
            CityFAQ("Why does UrbanAir show a worst-time block?", "It helps you avoid the least comfortable period for errands and exercise."),
        ),
    ),
    "bhubaneswar": CityConfig(
        slug="bhubaneswar",
        name="Bhubaneswar",
        state="Odisha",
        lat=20.2961,
        lon=85.8245,
        timezone="Asia/Kolkata",
        hero_title="Bhubaneswar AQI and today's best time to step outside",
        meta_description="Check Bhubaneswar AQI now, compare near-term outdoor conditions, and get practical daily outdoor guidance.",
        intro="UrbanAir turns Bhubaneswar air quality into an easy timing decision for errands, walks, and home ventilation.",
        commuter_tip="If the current score is weak, a later window may be better for a short walk or ride.",
        sensitive_tip="Sensitive users should use the highlighted worst-time block as a clear avoid signal for strenuous activity.",
        affiliate_focus="home purification essentials",
        related_slugs=("kolkata", "patna", "ranchi"),
        faqs=(
            CityFAQ("Why does Bhubaneswar need hourly guidance?", "Because the practical choice is often whether to go now or wait."),
            CityFAQ("Should I ventilate my home in Bhubaneswar today?", "Only during the recommended ventilation period for the current conditions."),
        ),
    ),
}


def list_cities() -> list[CityConfig]:
    return sorted(CITY_REGISTRY.values(), key=lambda city: city.name)


def get_city(slug: str) -> CityConfig | None:
    return CITY_REGISTRY.get(slug.lower())
